export enum AuditAction {
  CREATE_FAMILY_TREE = 'CREATE_FAMILY_TREE',
  CREATE_PERSON = 'CREATE_PERSON',
  ESTABLISH_PARENT_CHILD = 'ESTABLISH_PARENT_CHILD',
  ESTABLISH_SPOUSE = 'ESTABLISH_SPOUSE',
  REMOVE_RELATIONSHIP = 'REMOVE_RELATIONSHIP',
  REMOVE_PERSON = 'REMOVE_PERSON',
  IMPORT_PERSONS = 'IMPORT_PERSONS',
  ADD_MEMBER = 'ADD_MEMBER',
  REMOVE_MEMBER = 'REMOVE_MEMBER',
  CHANGE_MEMBER_ROLE = 'CHANGE_MEMBER_ROLE',
  TRANSFER_OWNERSHIP = 'TRANSFER_OWNERSHIP',
}
